name: dart_auth
description: A starting point for Dart libraries or applications.
version: 1.0.1
repository: https://github.com/yuen-quinn/dart_auth

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  http: ^1.6.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
